name: Setup GO
on: workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v5

      - name: Setup Go
        id: setup-go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'
          cache: false

      - name: Set Go cache environment variables
        shell: bash
        if: runner.os != 'Windows'
        run: |
          echo "GO_MOD_CACHE=$(go env GOMODCACHE)" >> $GITHUB_ENV
          echo "GO_BUILD_CACHE=$(go env GOCACHE)" >> $GITHUB_ENV
      - name: Set Go cache environment variables (Windows)
        shell: pwsh
        if: runner.os == 'Windows'
        run: |
          echo "GO_MOD_CACHE=$(go env GOMODCACHE -w '/')" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "GO_BUILD_CACHE=$(go env GOCACHE -w '/')" | Out-File -FilePath $env:GITHUB_ENV -Append
      - name: Set IMAGE_OS
        shell: bash
        if: runner.os != 'Windows'
        run: |
          echo "IMAGE_OS=$ImageOS-" >> $GITHUB_ENV
      - name: Set IMAGE_OS (Windows)
        shell: pwsh
        if: runner.os == 'Windows'
        run: |
          echo "IMAGE_OS=" | Out-File -FilePath $env:GITHUB_ENV -Append
      - name: Save lowercase arch
        shell: bash
        if: runner.os != 'Windows'
        run: echo "ARCH=$(echo '${{ runner.arch }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Save lowercase arch (Windows)
        shell: pwsh
        if: runner.os == 'Windows'
        run: |
          $arch = "${{ runner.arch }}".ToLower()
          echo "ARCH=$arch" | Out-File -FilePath $env:GITHUB_ENV -Append
      - name: Restore Go cache
        uses: actions/cache/restore@v4
        id: go-cache
        with:
          path: |
            ${{ env.GO_MOD_CACHE }}
            ${{ env.GO_BUILD_CACHE }}
          key: setup-go-${{ runner.os }}-${{ env.ARCH }}-${{ env.IMAGE_OS }}-go-${{ steps.setup-go.outputs.go-version }}-${{ hashFiles('**/go.sum') }}

      - name: Download modules
        run: go mod download

      - name: Build
        run: go build ./...
