name: Setup GO
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Go
        id: setup
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'
          cache: false

      - name: Restore Go cache
        uses: actions/cache/restore@v4
        id: go-cache
        with:
          path: |
            $GOMODCACHE
            $GOCACHE
          key: ${{ steps.setup.outputs.cache-primary-key }}
          restore-keys: |
            ${{ steps.setup.outputs.cache-prefix }}

      - name: Download modules
        run: go mod download

      - name: Build
        run: go build ./...
