name: Test Go Cache Keys Across Runners

on: push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5

      # Setup Go without caching
      - name: Setup Go
        id: setup-go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'
          cache: false

      # Normalize arch
      - name: Save lowercase arch
        shell: bash
        run: echo "ARCH=$(echo ${{ runner.arch }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # Normalize IMAGE_OS (Linux, Windows, macOS)
      - name: Set IMAGE_OS
        shell: bash
        run: |
          # GitHub exposes ImageOS differently per runner type.
          
          if [ "${{ runner.os }}" = "Linux" ]; then
            echo "IMAGE_OS=${ImageOS}-" >> $GITHUB_ENV
          elif [ "${{ runner.os }}" = "Windows" ]; then
            echo "IMAGE_OS=${ImageOS}-" >> $GITHUB_ENV
          elif [ "${{ runner.os }}" = "macOS" ]; then
            echo "IMAGE_OS=${ImageOS}-" >> $GITHUB_ENV
          else
            echo "IMAGE_OS=" >> $GITHUB_ENV
          fi

      # Show debugging info
      - name: Print env info
        run: |
          echo "OS: ${{ runner.os }}"
          echo "ARCH: $ARCH"
          echo "IMAGE_OS: $IMAGE_OS"

      # Restore Go cache
      - name: Restore Go cache
        uses: actions/cache/restore@v4
        id: go-cache
        with:
          path: |
            ${{ env.GOMODCACHE }}
            ${{ env.GOCACHE }}
          key: setup-go-${{ runner.os }}-${{ env.ARCH }}-${{ env.IMAGE_OS }}go-${{ steps['setup-go'].outputs.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            setup-go-${{ runner.os }}-${{ env.ARCH }}-${{ env.IMAGE_OS }}go-${{ steps['setup-go'].outputs.go-version }}-
            setup-go-${{ runner.os }}-

      - name: Download modules
        run: go mod download

      - name: Build
        run: go build ./...
